### ISSUE TITLE
Request on Received is Empty

### ISSUE THREAD

**Issue by felipecaputo** [drauly/HttpMock.Net#1]
I was following the examples on ReadMe to use this lib to test my webhook application but, when validating the request, as the example shows, the request has no info:

![image](https://user-images.githubusercontent.com/7751449/53041744-850ae080-3463-11e9-8433-d4538f07c5b4.png)

PS: I'm using dotnet core 2.2 and xUnit

**Comment by drauly** [comment]
Hello,

```Received``` act as an Assert method, so you should just return your equality lambda : 

```csharp
server.Received(1, ctx => "/webhook/uuid-test".Equals(ctx.Request.Path))
```

That said, I don't know why you have a null path on your request. If you let Received method doing the assertion, it will throw you an exception with more infos. You can also watch the server instance during debug to see what's the content of field ```_receivedRequests```

**Comment by felipecaputo** [comment]
Hi @drauly, thank you for your quick reply.

I've done that, using a variable to hold my received request. It worked perfectly. I'll try to return directly and see if the request information is present and let you know.

By the way, congratulations, your package saved a lot of mocking inside `HttpClient` and some unnecessary dependency injection.

**Comment by drauly** [comment]
Ok, nice !

Glad to hear that this lib can be usefull for you !
